VERSION 0.8

IMPORT ../../.. AS core

deploy:
    FROM --pass-args core+deployer-image
    RUN helm upgrade --install \
        --namespace kube-system \
        --create-namespace \
        --repo https://emberstack.github.io/helm-charts \
        reflector reflector
        