VERSION 0.8

IMPORT ../../.. AS core

deploy:
    FROM --pass-args core+deployer-image
    COPY values.yaml values.yaml
    RUN helm upgrade --install \
        --kube-insecure-skip-tls-verify \
        --namespace cert-manager \
        --create-namespace \
        --values values.yaml \
        --version v1.12.9 \
        --repo https://charts.jetstack.io \
        cert-manager cert-manager
