VERSION 0.8

IMPORT ../../.. AS core

deploy:
    FROM --pass-args core+deployer-image
    ARG tld=dev.formance.theweirdlab.me
    COPY values.yaml .
    RUN helm upgrade --install \
        --namespace kube-system \
        --create-namespace \
        --values values.yaml \
        --repo https://traefik.github.io/charts \
        traefik traefik
        