VERSION 0.8

IMPORT ../../.. AS core

deploy:
    FROM --pass-args core+deployer-image
    COPY *.yaml .
    RUN helm upgrade --install \
        --namespace formance \
        --create-namespace otel-collector \
        --values values.yaml \
        --repo https://open-telemetry.github.io/opentelemetry-helm-charts \
        opentelemetry-collector