VERSION 0.8

IMPORT ../../.. AS core

deploy:
    FROM --pass-args core+deployer-image
    COPY --dir charts/buildkitd ./chart
    COPY values.yaml .
    RUN helm upgrade --install \
        --namespace tools \
        --values values.yaml \
        --create-namespace \
        buildkit ./chart --debug
