apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingress-route-{{ .Values.user }}
spec:
  routes:
    - match: HostSNI(`kube.{{ .Values.user }}.{{ .Values.tld }}`)
      services:
        - name: {{ .Values.user }}
          port: https
  tls:
    passthrough: true