membership:
  enabled: true
  version: 1
agent:
  enabled: true
  version: 1
stargate:
  enabled: true
  version: 1
console:
  enabled: true
  version:
platform:
  enabled: true
  version:
gateway:
  enabled: true
  version:
ledger:
  enabled: true
  version:
payments:
  enabled: true
  version:
wallets:
  enabled: true
  version:
analytics:
  enabled: true
  version:
reconciliation:
  enabled: true
  version:
orchestration:
  enabled: true
  version:
auth:
  enabled: true
  version:
search:
  enabled: true
  version:
