VERSION 0.8

IMPORT ../../.. AS core

deploy:
    FROM --pass-args core+deployer-image
    COPY *.yaml .
    RUN helm upgrade --install \
        --namespace tools \
        --create-namespace \
        --values values.yaml \
        --set persistence.enabled=true \
        --repo https://helm.twun.io \
        ghcr-registry docker-registry
    RUN helm upgrade --install \
        --namespace tools \
        --create-namespace \
        --values values-write.yaml \
        --set persistence.enabled=true \
        --repo https://helm.twun.io \
        ghcr-registry-write docker-registry
