VERSION --pass-args 0.7

IMPORT ../../.. AS core

deploy:
    FROM --pass-args core+deployer-image
    COPY --dir chart .
    RUN --secret tld helm upgrade --install jaeger ./chart \
        --namespace tools \
        --create-namespace \
        --set tld=$tld